# Generated by Django 4.2.3 on 2023-08-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
