# Generated by Django 4.2.4 on 2024-01-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='F', max_length=1),
        ),
    ]
