# Generated by Django 4.2.4 on 2024-02-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sex',
            new_name='gender',
        ),
    ]
