# Generated by Django 4.2.3 on 2023-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_this_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='this_one',
            field=models.BooleanField(unique=True),
        ),
    ]
