# Generated by Django 4.2.4 on 2024-01-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_this_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='departments',
        ),
    ]
