# Generated by Django 4.2.4 on 2024-01-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='departments',
        ),
    ]
