# Generated by Django 4.2.4 on 2024-02-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='record',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='record',
            name='procedure_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recommendations',
        ),
    ]
