# Generated by Django 4.2.4 on 2024-02-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_organization'),
        ('users', '0016_alter_profile_medical_field'),
        ('records', '0002_remove_record_diagnosis_remove_record_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AddField(
            model_name='record',
            name='diagnosis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='record',
            name='findings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='record',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='record',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
