# Generated by Django 4.2.4 on 2024-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_department_record_diagnosis_record_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.JSONField(default=dict),
        ),
    ]
