# Generated by Django 4.2.4 on 2024-02-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_medical_field'),
        ('records', '0004_record_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.JSONField(default=dict)),
                ('findings', models.JSONField(default=dict)),
                ('diagnosis', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=dict)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
