# Generated by Django 4.2.4 on 2024-02-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='diagnosis_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema'),
        ),
        migrations.AddField(
            model_name='template',
            name='findings_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema'),
        ),
        migrations.AddField(
            model_name='template',
            name='recommendations_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema'),
        ),
        migrations.AddField(
            model_name='template',
            name='record_type_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema'),
        ),
    ]
