# Generated by Django 4.2.4 on 2024-02-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_schema_template_diagnosis_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='template',
            name='diagnosis_schema',
        ),
        migrations.RemoveField(
            model_name='template',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='template',
            name='recommendations_schema',
        ),
        migrations.RemoveField(
            model_name='template',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='record_type_schema',
        ),
        migrations.AlterField(
            model_name='template',
            name='findings_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema'),
        ),
    ]
