# Generated by Django 4.2.4 on 2024-02-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_organization'),
        ('records', '0007_remove_record_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='specialist',
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='record_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.recordtype'),
        ),
    ]
