# Generated by Django 4.2.4 on 2024-02-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_template_specialist_recordtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='department',
        ),
    ]
