# Generated by Django 4.2.4 on 2024-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_record_findings_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='ui_schema',
            field=models.JSONField(default=dict),
        ),
    ]
