# Generated by Django 4.2.4 on 2024-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_schema_ui_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schema',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
