# Generated by Django 4.2.4 on 2024-03-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_schema_schema_alter_schema_ui_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.recordtype'),
        ),
    ]
