# Generated by Django 4.2.4 on 2024-03-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_rename_description_schema_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='name_old',
            new_name='description',
        ),
    ]
