# Generated by Django 4.2.4 on 2024-03-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_rename_description_schema_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='name_old',
        ),
    ]
