# Generated by Django 4.2.4 on 2024-03-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_organization'),
        ('records', '0020_remove_schema_name_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
    ]
