# Generated by Django 4.2.4 on 2024-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_schema_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
