# Generated by Django 4.2.4 on 2024-03-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_schema_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='record_type',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
