# Generated by Django 4.2.4 on 2024-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_remove_record_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
