# Generated by Django 4.2.4 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_record_is_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
