# Generated by Django 4.2.4 on 2024-03-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_department_organization'),
        ('records', '0025_delete_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_template',
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.JSONField(default=dict)),
                ('template_name', models.CharField(max_length=255)),
                ('template_slug', models.SlugField(max_length=255, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('findings_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.schema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
