# Generated by Django 4.2.1 on 2023-05-16 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('manager', 'Manager'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(max_length=12)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('medical_field', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
