# Generated by Django 4.2.1 on 2023-05-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='Organization',
        ),
    ]
