# Generated by Django 4.2.3 on 2023-07-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0003_remove_profile_departments_profile_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='departments',
        ),
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
            preserve_default=False,
        ),
    ]
