# Generated by Django 4.2.3 on 2023-07-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_departments_profile_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.medicalfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.position'),
        ),
    ]
