# Generated by Django 4.2.3 on 2023-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_medical_field_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('DC', 'doctor'), ('NS', 'nurse'), ('MN', 'manager'), ('AD', 'admin')], default='US', max_length=20),
        ),
    ]
