# Generated by Django 4.2.4 on 2024-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('DC', 'doctor'), ('NS', 'nurse'), ('CO', 'coordinator'), ('AD', 'admin')], default='US', max_length=20),
        ),
    ]
