# Generated by Django 4.2.4 on 2024-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfield',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('DC', 'doctor'), ('NS', 'nurse'), ('CO', 'coordinator'), ('AD', 'admin')], default='US', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('DC', 'doctor'), ('NS', 'nurse'), ('CO', 'coordinator'), ('AD', 'admin')], default='US', max_length=100),
        ),
    ]
