# Generated by Django 4.2.4 on 2024-01-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_medicalfield_role_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medicalfield'),
        ),
    ]
