# Generated by Django 4.2.4 on 2024-01-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicalfield'),
        ),
    ]
